on:
  pull_request:
  push:

jobs:
  firmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build firmware
      working-directory: firmware
      run: nix develop -L .#ci --command idf.py build

  hardware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build interactive bom
      run: |
        nix develop -L .#hardware --command \
          generate_interactive_bom --no-browser --layer-view F hardware/power-monitor.kicad_pcb --dest-dir public --name-format index
      env:
        INTERACTIVE_HTML_BOM_NO_DISPLAY: 1

    - name: Export PDF Schmetics
      run: |
        nix develop -L .#hardware --command \
          kicad-cli sch export pdf --output public/power-monitor.pdf hardware/power-monitor.kicad_sch

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./hardware/public

  deploy:
    needs: hardware

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
